name: "Trend Cloud One Container Security Scan Action"
description: "Scan container images with Trend Cloud One Container Security"
author: "Trend Micro"
inputs:
  CLOUD_ONE_API_KEY:
    description: "Cloud One API Key"
    required: true
  IMAGE:
    description: "Image URI to scan. Not required if you are doing pre-registry scanning. See LOCAL_IMAGE_TARBALL."
    required: false
  REGION:
    description: "Cloud One Region"
    required: true
    default: "us-1"
  SBOM:
    description: "Decide if you want to save the SBOM file for the image. Default is true."
    required: false
    default: "true"
  MAX_TOTAL:
    description: "Max total of vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_CRITICAL:
    description: "Max critical vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_HIGH:
    description: "Max high vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_MEDIUM:
    description: "Max medium vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_LOW:
    description: "Max low vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_NEGLIGIBLE:
    description: "Max negligible vulnerabilities acceptable in a images"
    required: false
    default: "0"
  MAX_UNKNOWN:
    description: "Max unknown vulnerabilities acceptable in a images"
    required: false
    default: "0"
  SCAN_RESULT_ARTIFACT:
    description: "Name for the artifact generated by the scan in case you want to archive it."
    required: false
    default: "scan-result.json"
  LOCAL_IMAGE_TARBALL:
    description: "Name for the locally available image tarball in case you are doing pre-registry scanning."
    required: false
branding:
  icon: "package"
  color: "red"
runs:
  using: "docker"
  image: "docker://ghcr.io/trendmicro/container-security-scan-action:latest"
  env:
    CLOUD_ONE_API_KEY: ${{ inputs.CLOUD_ONE_API_KEY }}
    IMAGE: ${{ inputs.IMAGE }}
    REGION: ${{ inputs.REGION }}
    SBOM: ${{ inputs.SBOM }}
    MAX_TOTAL: ${{ inputs.MAX_TOTAL }}
    MAX_CRITICAL: ${{ inputs.MAX_CRITICAL }}
    MAX_HIGH: ${{ inputs.MAX_HIGH }}
    MAX_MEDIUM: ${{ inputs.MAX_MEDIUM }}
    MAX_LOW: ${{ inputs.MAX_LOW }}
    MAX_NEGLIGIBLE: ${{ inputs.MAX_NEGLIGIBLE }}
    MAX_UNKNOWN: ${{ inputs.MAX_UNKNOWN }}
    SCAN_RESULT_ARTIFACT: ${{ inputs.SCAN_RESULT_ARTIFACT }}
    LOCAL_IMAGE_TARBALL: ${{ inputs.LOCAL_IMAGE_TARBALL }}